const backdrop=document.querySelector('#backdrop'),choice=document.querySelector('#choice'),formBox=document.querySelector('#form'),success=document.querySelector('#success'),typeInput=document.querySelector('#type'),form=document.querySelector('#leadForm'),formTitle=document.querySelector('#formTitle'),formEyebrow=document.querySelector('#formEyebrow'),submit=document.querySelector('#submit');
let selected='content';
function reset(){choice.classList.remove('hidden');formBox.classList.add('hidden');success.classList.add('hidden');form.reset();document.querySelectorAll('form label>span').forEach(x=>x.textContent='');document.querySelectorAll('form input').forEach(x=>x.classList.remove('invalid'))}
function openModal(type='choose'){reset();backdrop.classList.add('open');document.body.classList.add('modal-open');if(type==='consultation')setType('consultation')}
function closeModal(){backdrop.classList.remove('open');document.body.classList.remove('modal-open')}
function setType(type){selected=type;typeInput.value=type;choice.classList.add('hidden');formBox.classList.remove('hidden');if(type==='consultation'){formEyebrow.textContent='AI WORK CONSULTATION';formTitle.innerHTML='상담을 신청하려면<br>정보를 입력해주세요.';submit.innerHTML='상담 신청하기 →'}else{formEyebrow.textContent='AI PRACTICAL CONTENT';formTitle.innerHTML='콘텐츠를 받아보려면<br>정보를 입력해주세요.';submit.innerHTML='콘텐츠 받기 →'}}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));
document.querySelectorAll('.choices button').forEach(b=>b.addEventListener('click',()=>setType(b.dataset.type)));
document.querySelector('#close').addEventListener('click',closeModal);document.querySelector('#done').addEventListener('click',closeModal);document.querySelector('#back').addEventListener('click',()=>{formBox.classList.add('hidden');choice.classList.remove('hidden')});backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&backdrop.classList.contains('open'))closeModal()});
document.querySelector('#phone').addEventListener('input',e=>{let d=e.target.value.replace(/\D/g,'').slice(0,11);e.target.value=d.length<4?d:d.length<8?`${d.slice(0,3)}-${d.slice(3)}`:d.length===10?`${d.slice(0,3)}-${d.slice(3,6)}-${d.slice(6)}`:`${d.slice(0,3)}-${d.slice(3,7)}-${d.slice(7)}`});
function error(id,msg){const i=document.querySelector('#'+id);i.classList.add('invalid');i.parentElement.querySelector('span').textContent=msg}
form.addEventListener('submit',e=>{e.preventDefault();document.querySelectorAll('form label>span').forEach(x=>x.textContent='');let ok=true,n=document.querySelector('#name'),em=document.querySelector('#email'),ph=document.querySelector('#phone');if(!n.value.trim()){error('name','이름을 입력해주세요.');ok=false}if(!em.value.trim())error('email','이메일을 입력해주세요.'),ok=false;else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em.value.trim()))error('email','올바른 이메일 주소를 입력해주세요.'),ok=false;if(ph.value.replace(/\D/g,'').length<10)error('phone','올바른 전화번호를 입력해주세요.'),ok=false;if(!document.querySelector('#privacy').checked){ok=false;alert('필수 약관에 동의해주세요.')}if(!ok)return;console.log('Lead:',Object.fromEntries(new FormData(form).entries()));formBox.classList.add('hidden');success.classList.remove('hidden');document.querySelector('#successTitle').textContent=selected==='consultation'?'상담 신청이 완료되었습니다.':'신청이 완료되었습니다.';document.querySelector('#successText').textContent=selected==='consultation'?'입력하신 연락처로 상담 관련 안내를 드립니다.':'입력하신 이메일로 AI 실무 활용 콘텐츠를 보내드립니다.'});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
